[custom.all.bytestring]
type   = "local"
path   = "."
ipkg   = "bytestring.ipkg"
test   = "test/test.ipkg"

[custom.all.bytestring-test]
type   = "local"
path   = "test"
ipkg   = "test.ipkg"

[custom.all.bytestring-profile]
type   = "local"
path   = "profile"
ipkg   = "profile.ipkg"

[custom.all.ref1]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-ref1"
commit = "latest:main"
ipkg   = "ref1.ipkg"

[custom.all.array]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-array"
commit = "latest:main"
ipkg   = "array.ipkg"
